image: $CI_DOCKER_REMOTE_NAME/irhawks/docker:stable

services:
  - $CI_DOCKER_REMOTE_NAME/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME

build-maven:
  stage: build
  script:
  - cd maven
  - docker build -t $CI_DOCKER_UPLOAD_NAME/irhawks/maven:default .
deploy-maven:
  stage: deploy
  script:
  - cd maven
  - docker push $CI_DOCKER_UPLOAD_NAME/irhawks/maven:default
