image: ${CI_DOCKER_REMOTE_NAME}/irhawks/docker:stable

services:
  - ${CI_DOCKER_REMOTE_NAME}/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME

maven:
  stage: build
  only:
    changes:
      - maven/*
  script:
  - cd maven
  - export TAG=v`date +%Y%m%d`
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:$TAG .
  - docker push ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:$TAG

## 基于rstudio所构建的镜像不太可行，还是需要自己用ubuntu
.r-testthat:
  stage: build
  only:
    - master
  script:
  - cd r/testthat
  - export TAG=v`date +%Y%m%d`
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1$TAG .
  - docker push ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1$TAG


ubuntu:
  variables:
    UBUNTU_BASE_IMAGE_VERSION: "18.04"
    #UBUNTU_APT_REMOTE_NAME: "http://mirrors4.tuna.tsinghua.edu.cn/ubuntu"
    UBUNTU_APT_REMOTE_NAME: "http://int.nexus.irhawks.com/repository/apt-tsinghua/"
    CRAN_REMOTE_NAME: "http://mirrors4.tuna.tsinghua.edu.cn/CRAN"
    #REMOTE_RESOURCE_URL: http://repo:9990
    #REMOTE_BULKLOAD_URL: http://repo:9991
    #REMOTE_FULLLOAD_URL: http://repo:9992
    #REMOTE_APTCACHE_URL: http://repo:9993
    ### backup vars
    #UBUNTU_APT_REMOTE_NAME: APTCACHE_URL/ubuntu
    #CRAN_REMOTE_NAME: APTCACHE_URL/CRAN
  before_script:
    - export DOCKER_MAINLAND_BUILD_ARGS="--build-arg UBUNTU_APT_REMOTE_NAME=${UBUNTU_APT_REMOTE_NAME} --build-arg CRAN_REMOTE_NAME=${CRAN_REMOTE_NAME}"
    - export DOCKER_INTERNAL_BUILD_ARGS="--build-arg UBUNTU_APT_REMOTE_NAME=${UBUNTU_APT_REMOTE_NAME} --build-arg REMOTE_RESOURCE_URL=${REMOTE_RESOURCE_URL} --build-arg REMOTE_BULKLOAD_URL=${REMOTE_BULKLOAD_URL}"
    - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME
    - export
    - export TAG=v`date +%Y%m%d`
  script:
    - cd ubuntu
    - docker build $DOCKER_MAINLAND_BUILD_ARGS -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/ubuntu/base:18.04$TAG -f env.Dockerfile .
    - docker push ${CI_DOCKER_UPLOAD_NAME}/irhawks/ubuntu/base:18.04$TAG

## 基于构建出来的ubuntu来构建R镜像 
rlang-ci:
  variables:
    #CRAN_REMOTE_NAME: "http://mirrors4.tuna.tsinghua.edu.cn/CRAN"
    CRAN_REMOTE_NAME: "http://int.nexus.irhawks.com/repository/cran"
  only:
    changes:
      - r/*
  before_script:
    - export DOCKER_MAINLAND_BUILD_ARGS="--build-arg CRAN_REMOTE_NAME=${CRAN_REMOTE_NAME}"
    - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME
    - export
  script:
    - cd r
    - export TAG=irhawks/rlang/ci-default:v`date +%Y%m%d`
    - |
      echo "Building default images"
      docker build $DOCKER_MAINLAND_BUILD_ARGS -t ${CI_DOCKER_UPLOAD_NAME}/$TAG -f ci-full .
      docker push ${CI_DOCKER_UPLOAD_NAME}/$TAG

    - export TAG=irhawks/rlang/ci-full:v`date +%Y%m%d`
    - |
      echo "Upload full images"
      docker build $DOCKER_MAINLAND_BUILD_ARGS -t ${CI_DOCKER_UPLOAD_NAME}/$TAG -f ci-full .
      docker push ${CI_DOCKER_UPLOAD_NAME}/$TAG

sbt-default:
  variables:
  only:
    changes:
      - scala/*
  before_script:
    - export DOCKER_MAINLAND_BUILD_ARGS="--build-arg CRAN_REMOTE_NAME=${CRAN_REMOTE_NAME}"
    - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME
  script:
    - |
      cd scala
      export TAG=irhawks/scala/ci-default:v`date +%Y%m%d`
      docker build $DOCKER_MAINLAND_BUILD_ARGS -t ${CI_DOCKER_UPLOAD_NAME}/$TAG -f Dockerfile .
      docker push ${CI_DOCKER_UPLOAD_NAME}/$TAG

