image: $CI_DOCKER_REMOTE_NAME/irhawks/docker:stable

services:
  - $CI_DOCKER_REMOTE_NAME/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME

maven:
  stage: build
  only:
    - master
  script:
  - cd maven
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:default .
  - docker push ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:default

r-testthat:
  stage: build
  only:
    - master
  script:
  - cd r/testthat
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1 .
  - docker push -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1
