image: ${CI_DOCKER_REMOTE_NAME}/irhawks/docker:stable

services:
  - ${CI_DOCKER_REMOTE_NAME}/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_DOCKER_UPLOAD_USER --password $CI_DOCKER_UPLOAD_PASS $CI_DOCKER_UPLOAD_NAME

maven:
  stage: build
  only:
    - master
  script:
  - cd maven
  - export TAG=v`date +%Y%m%d`
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:$TAG .
  - docker push ${CI_DOCKER_UPLOAD_NAME}/irhawks/maven:$TAG

r-testthat:
  stage: build
  only:
    - master
  script:
  - cd r/testthat
  - export TAG=v`date +%Y%m%d`
  - docker build -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1$TAG .
  - docker push -t ${CI_DOCKER_UPLOAD_NAME}/irhawks/rlang-ci:3.4.1$TAG


ubuntu:
  variables:
    UBUNTU_BASE_IMAGE_VERSION: 18.04
    UBUNTU_APT_REMOTE_NAME: http://mirrors4.tuna.tsinghua.edu.cn/ubuntu
    CRAN_REMOTE_NAME: http://mirrors4.tuna.tsinghua.edu.cn/CRAN
    REMOTE_RESOURCE_URL: http://repo:9990
    REMOTE_BULKLOAD_URL: http://repo:9991
    REMOTE_FULLLOAD_URL: http://repo:9992
    REMOTE_APTCACHE_URL: http://repo:9993
 vars_backup:
    UBUNTU_APT_REMOTE_NAME: ${APTCACHE_URL}/ubuntu
    CRAN_REMOTE_NAME: ${APTCACHE_URL}/CRAN
  
 before_script:
   - export DOCKER_MAINLAND_BUILD_ARGS="--build-arg UBUNTU_APT_REMOTE_NAME=${UBUNTU_APT_REMOTE_NAME}"
   - export DOCKER_INTERNAL_BUILD_ARGS="--build-arg UBUNTU_APT_REMOTE_NAME=${UBUNTU_APT_REMOTE_NAME} --build-arg REMOTE_RESOURCE_URL=${REMOTE_RESOURCE_URL} --build-arg REMOTE_BULKLOAD_URL=${REMOTE_BULKLOAD_URL}"
