image: $CI_REGISTRY_REPONAME/irhawks/docker:stable

services:
  - $CI_REGISTRY_REPONAME/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_REGISTRY_USERNAME --password $CI_REGISTRY_PASSWORD $CI_REGISTRY_REPONAME

build-maven:
  stage: build
  script:
  - cd maven && docker build -t $CI_REGISTRY_REPONAME/irhawks/maven:default
  - docker push $CI_REGISTRY_REPONAME/irhawks/maven:default
