image: $CI_DOCKER_REGISTRY_REPO_NAME/irhawks/docker:stable

services:
  - $CI_DOCKER_REGISTRY_REPO_NAME/irhawks/docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker login --username $CI_DOCKER_REGISTRY_USER --password $CI_DOCKER_REGISTRY_PASS $CI_DOCKER_REGISTRY_REPO_NAME

build-maven:
  stage: build
  script:
  - cd maven && docker build -t $CI_DOCKER_REGISTRY_REPO_NAME/irhawks/maven:default
  - docker push $CI_DOCKER_REGISTRY_REPO_NAME/irhawks/maven:default
